package cov.mjp.eclipsemap;

public class Address {
	
	private final int houseNumber;
	private final String street;
	private final String town;
	
	public Address(int houseNumber, String street, String town) {
		this.houseNumber = houseNumber;
		this.street = street;
		this.town = town;
	}

	/** This method has been auto-generated by Eclipse. Alt+Shift+s, then s. */
	@Override
	public String toString() {
		return "Address [houseNumber=" + houseNumber + ", street=" + street + ", town=" + town + "]";
	}
	
}
