package cov.mjp.eclipsemap;

public class Name {
	
	private final Title title;
	private final String forename;
	private final String surname;
	
	public Name(Title title, String forename, String surname) {
		this.title = title;
		this.forename = forename;
		this.surname = surname;
	}

	/** This method has been auto-generated by Eclipse. Alt+Shift+s, then s. */
	@Override
	public String toString() {
		return "Name [title=" + title + ", forename=" + forename + ", surname=" + surname + "]";
	}
	
}
