package cov.mjp.eclipsemap;

public class President {

	private final String country;
	private final Name name;
	private final Address address;
	
	public President(String country, Name name, Address address) {
		this.country = country;
		this.name = name;
		this.address = address;
	}

	/** This method has been auto-generated by Eclipse. Alt+Shift+s, then s. */
	@Override
	public String toString() {
		return "President [country=" + country + ", name=" + name + ", address=" + address + "]";
	}
}
